# Generated by Django 5.2.8 on 2025-11-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('functionSummary', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
