# Generated by Django 5.2.8 on 2025-11-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genosentinelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='functionSummary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=1000)),
                ('position', models.BigIntegerField()),
                ('reference_base', models.CharField(db_column='referenceBase', max_length=10)),
                ('alternate_base', models.CharField(db_column='alternateBase', max_length=10)),
                ('impact', models.CharField(max_length=50)),
                ('gene', models.ForeignKey(db_column='geneId', on_delete=django.db.models.deletion.CASCADE, to='genosentinelapp.gene')),
            ],
            options={
                'db_table': 'geneticvariant',
            },
        ),
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.BigIntegerField(db_column='patientId')),
                ('detection_date', models.DateField(db_column='detectionDate')),
                ('allele_frequency', models.DecimalField(db_column='alleleFrequency', decimal_places=4, max_digits=5)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genosentinelapp.geneticvariant')),
            ],
        ),
    ]
